[package]
name = "sakuramml"
version = "0.1.13"
edition = "2021"
authors = ["kujirahand <web@kujirahand.com>"]
rust-version = "1.64.0"
description = "sakuramml is MML/ABC to MIDI Compiler"
readme = "README.md"
homepage = "https://sakuramml.com"
repository = "https://github.com/kujirahand/sakuramml-rust"
license = "MIT"
license-file = "LICENSE"
keyword = ["MML", "MIDI", "MML to MIDI Compiler", "ABC"]
exclude = ["/test.sh"]

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2"

